name: HatMe
main: net.serubin.hatme.HatMe
version: ${project.version}

commands:
  hat:
    aliases: [hat, hatme, hm]
    description: Command that puts the item on your head.
    usage: /<command> - puts item on head
  unhat:
    aliases: [unhat, unhatme, unhm]
    description: Command to take your "hat" off.
    usage: /<command> - takes item off head
permissions:
  hatme.*:
    description: gives full permission on Hatme.
    children:
      hatme.hat: true
      hatme.norestrict: true
      hatme.hat.give: true
      hatme.hat.all: true
  hatme.hat:
    description: gives permission on /hat.
    default: true
  hatme.norestrict:
    description: gives permission on /hat with no restrictions.
    default: op
  hatme.hat.give:
    description: gives full permission on /hat.
    default: op
    children:
      hatme.hat: true