name: hatMe
main: com.shloms.serubin.hatme.HatMe
version: 0.6.6

commands:
   hat:
      aliases: [hat, hatme, hm]
      description: Command that puts the item on your head.
      usage: /<command> [item id]- puts item on head [puts item on head from item id]
   unhat:
      aliases: [unhat, unhatme, unhm]
      description: Command to take your "hat" off.
      usage: /<command> - takes item off head